--------------------------------------------------------
-- MySQL Schema Script
-- MySQL Server 5.6.31
-- MySQL Workbench (6.3.7 CE) Forward Engineering
-- -----------------------------------------------------
-- Schema test
-- Tables starting with TL_ can be easily indentified as my application tables
-- in DB if there are other applications in the same DB.